# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -maxim.razumkov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="0d6ec09b-7ef3-4dff-b219-555a8f6c3728"